steps:
  - label: "buck2-haskell"
    commands:
      - git clone https://github.com/MercuryTechnologies/buck2-haskell
      - nix-shell --run 'buck clean'
      - nix-shell --run 'buck test buck2-haskell//tests/...'
    agents:
      queue: "self-hosted-linux"
